version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: assignmentdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./server
    volumes:
      - ./server:/app
      - ./server/uploaded_files:/app/uploaded_files
      - ./data/chroma:/data/chroma
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPAPI_KEY=${SERPAPI_KEY}
      - DATABASE_URL=postgresql://user:password@postgres:5432/assignmentdb
      - CHROMA_PERSIST_DIR=/data/chroma
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
